```{r}
# Establecer el directorio de trabajo
if (interactive()) {
    current_folder <- rstudioapi::getActiveDocumentContext()$path
    setwd(dirname(current_folder))
}
```

```{r}
library(keras)
library(reticulate)
# Data Preparation -----------------------------------------------------

batch_size <- 128
num_classes <- 10
epochs <- 12

# Input image dimensions
img_rows <- 28
img_cols <- 28

# The data, shuffled and split between train and test sets
mnist <- dataset_mnist()
x_train <- mnist$train$x
y_train <- mnist$train$y
x_test <- mnist$test$x
y_test <- mnist$test$y
```

```{r}
x_train <- array_reshape(x_train, c(nrow(x_train), img_rows, img_cols, 1))
x_test <- array_reshape(x_test, c(nrow(x_test), img_rows, img_cols, 1))
input_shape <- c(img_rows, img_cols, 1)

# Transform RGB values into [0,1] range
x_train <- x_train / 255
x_test <- x_test / 255

cat("x_train_shape:", dim(x_train), "\n")
cat(nrow(x_train), "train samples\n")
cat(nrow(x_test), "test samples\n")

# Convert class vectors to binary class matrices
y_train <- to_categorical(y_train, num_classes)
y_test <- to_categorical(y_test, num_classes)
```

```{r}
# Define Model -----------------------------------------------------------

model <- keras_model_sequential()
model %>%
    layer_conv_2d(
        filters = 32, kernel_size = c(3, 3), activation = "relu",
        input_shape = input_shape
    ) %>%
    layer_conv_2d(filters = 50, kernel_size = c(3, 3), activation = "relu") %>%
    layer_max_pooling_2d(pool_size = c(2, 2)) %>%
    layer_dropout(rate = 0.25) %>%
    layer_flatten() %>%
    layer_dense(units = 128, activation = "relu") %>%
    layer_dropout(rate = 0.5) %>%
    layer_dense(units = num_classes, activation = "softmax")

# Compile model
model %>% compile(
    loss = loss_categorical_crossentropy,
    optimizer = optimizer_adadelta(),
    metrics = c("accuracy")
)
summary(model)
```

```{r}
model %>% fit(
    x_train, y_train,
    batch_size = batch_size,
    epochs = epochs,
    verbose = 1,
    validation_data = list(x_test, y_test)
)
scores <- model %>% evaluate(
    x_test, y_test,
    verbose = 2
)

# Output metrics
cat("Test loss:", scores[[1]], "\n")
cat("Test accuracy:", scores[[2]], "\n")

# Calcular el score f1 con los resultados obtenidos
library(MLmetrics)
classes <- 0:(num_classes - 1)
f1_scores <- sapply(classes, function(cl) {
    true_binary <- as.integer(y_true == cl)
    pred_binary <- as.integer(y_pred == cl)
    F1_Score(y_true = true_binary, y_pred = pred_binary, positive = 1)
})
macro_f1 <- mean(f1_scores, na.rm = TRUE)
cat("Macro F1 score:", macro_f1, "\n")
```